variables:
  - key: scene
    scope: global
    type:
      type: string
      id: Qbp1ghXLRoUqy26x1Y4PXitzBw-5VtJm
    reset: true
    defaultValue: waterfull
  - key: userScene
    scope: user
    type:
      type: string
      id: _J5vIdcjqceouiIRw0i4nBtLLeq_xnVx
    reset: true
    defaultValue: ""
  - key: sessionScene
    scope: session
    type:
      type: string
      id: 4SKmLequecQm7bCQ8FM-yM5tbTi6RUYy
    reset: true
    defaultValue: ""
